version: '2'
services:
  db:
#    image: klaemo/couchdb:1.6.1
    build:
      context: simcity-couchdb
    ports:
      - "127.0.0.1:5784:5984"
      - "127.0.0.1:5884:5984"
    environment:
      COUCHDB_USER: simcityadmin
      COUCHDB_PASSWORD: simcity
  webdav:
    build:
      context: simcity-webdav
    ports:
      - "127.0.0.1:8080:80"
  slurm:
    build:
      context: simcity-slurm
    ports:
      - "127.0.0.1:10022:22"
    links:
      - db:taskdb
      - db:jobdb
      - webdav
  postgis:
    build:
      context: simcity-postgis
    ports:
      - "127.0.0.1:8082:8080"
  geoserver:
    build:
      context: simcity-geoserver
    ports:
      - "127.0.0.1:8081:8080"
    links:
      - postgis
  simcity_webservice:
    build:
      context: simcity-webservice
    ports:
      - "127.0.0.1:9098:9090"
      - "127.0.0.1:30022:22"
    links:
      - db:taskdb
      - db:jobdb
      - webdav
      - slurm
    volumes:
      - ./simcity-webservice/simulations/:/home/simcity/sim-city-webservice/simulations/
  nginx:
    build:
      context: simcity-nginx
    ports:
      - "127.0.0.1:8008:8008"
    links:
      - db:couchdb
      - webdav
      - simcity_webservice
      - postgis
      - geoserver
