version: '2'
services:
  backend:
    build:
      context:
        regis-backend
    ports:
      - "127.0.0.1:5984:5984"
      - "127.0.0.1:8008:80"
      - "127.0.0.1:20022:22"
    environment:
      COUCHDB_USER: simcityadmin
      COUCHDB_PASSWORD: simcity
  slurm:
    build:
      context: regis-slurm
    ports:
      - "127.0.0.1:10022:22"
    links:
      - backend
  simcity_webservice:
    build:
      context: simcity-webservice
    ports:
      - "127.0.0.1:9098:9090"
      - "127.0.0.1:30022:22"
    links:
      - backend
      - slurm
    volumes:
      - ./simcity-webservice/simulations/:/home/simcity/sim-city-webservice/simulations/
      - ./simcity-webservice/resources/:/home/simcity/sim-city-webservice/resources/
  commonsense:
    build:
      context: commonsense
    ports:
      - "127.0.0.1:3003:3003"
